n=input('Enter 1st string :')
n2=input('Enter 2nd string :')
n3=input('Enter 3rd string :')
n4=(n,n2,n3)
char=input('Enter you find index point of char in touple :')
print(n4.index(char))
input()