n=input('Enter 1st string :')
n2=input('Enter 2nd string :')
n3=input('Enter 3rd string :')
n4=(n,n2,n3)
print(n4)
char=input("Which char you want count in your tuple :")
print(n4.count(char))
input()