print('\n\n\t\t======> Enter your details <=====\n\n ')
name=input('Enter your name :')
marks=int(input('Enter your marks in matric :'))
percentage=float(input('Enter your percentage of matric marks :'))
grade=input('Enter your grade :')
section=input('Enter your section in school :')
ranking=input('Enter your ranking in school :')
ranking_2=input('Enter your ranking in your class :')
print('\n\n\t\t=====> Details are stored <=====\n\n')
print('\n\t\tYour Name is  :                 ',name)
print('\n\t\tYour Marks in matric is  :      ',marks)
print('\n\t\tYour Percentage in matric is  : ',percentage)
print('\n\t\tYour Grade in matric is  :      ',grade)
print('\n\t\tYour Section in school is  :    ',section)
print('\n\t\tYour Ranking in school  :       ',ranking)
print('\n\t\tYour Ranking in class room :    ',ranking_2)
input()