print('lineA \\n lineB')
print("\\\"\\\'")
print('this is 4 backslash \\\\\\\\')
print('lineA \\t lineB')
print("\\\\\\'")
print("\\\\\\\"")
print("\\\\\"\\\\\'")
print("haider\\\"")
print('haider\\\'')
input()