# name='haider'
# print(name[0:3])
# print(name[3:6])
# print(name[0:])
# print(name[:])
# print(name[:-1])
# print(name[-3:7])
name=input('enter your name :')
print('your name first alphabet remove :',name[1:])
input()