string=input('Enter a string :')
string2=input('which char you want to remove in your string :')
string3=input('New char you want in your string :')
string4=string.replace(string2,string3)
print(string4)
string5=input('thats char you want to find its position :')
string6=string.find(string5)
print(string6)
print('length of string is :',len(string))
input()