user=int(input('How many entery enter in list :'))
print('Enter',user,'entery :')
total=[]
for i in range(user):
    name=input()
    total.append(name)
print(total)
char=input('which char count in list :\n')
print(char,'present in ',total.count(char),' times :\n')
print('list in alphabetical order :\n')
print(sorted(total))
print('list copy :\n')
print(total.copy())
total.reverse()
print('Your list is reverse :\n')
print(total)
total.clear()
print('Your list is empty :\n')
print(total)
input()
