user_info={
    'name':'haider',
    'age':12,
}
print(user_info.items())
print(type(user_info))
print(user_info.keys())
print(type(user_info))
print(user_info.values())
print(type(user_info))
input()
