name=input("Enter your name :")
age=int(input('Enter your age :'))
clase=input('Enter your class :')
roll_no=input('Enter your roll_no :')
user_info=dict(name=name,age=age,clase=clase,roll_no=roll_no)
print(user_info)
input()